### ISSUE TITLE
HTML encoding on member names

### ISSUE THREAD

**Issue by konklone** [propublica/congress-api-docs#108]
Rep. Beto O'Rourke's name has his apostrophe turned into HTML encoding:

```json
{
   "status":"OK",
   "copyright":"Copyright (c) 2017 Pro Publica Inc. All Rights Reserved.",
   "results":[
      {
         "member_id": "O000170",
         
         "first_name": "Beto",
         "middle_name": null,
         "last_name": "O&#39;Rourke",
```

These should be decoded server-side, since the fields are expected to be plaintext strings.

**Comment by dwillis** [comment]
This should be fixed now.

**Comment by konklone** [comment]
Confirmed fixed. Thank you!

**Comment by konklone** [comment]
While this is fixed in many places, I am still seeing this in two places I've found:

* On bill info, as part of the sponsor name (and potentially cosponsor names, but haven't verified this yet)
* On committee and subcommittee member listings

I found this as part of a user report.

**Comment by dwillis** [comment]
Have fixed bill sponsor (cosponsors looked ok) and committee & subcommittee member names.

**Comment by konklone** [comment]
Looks fixed on committee listings, and for some/many bill sponsors, but I still see it on a couple of bills:

```
curl -s "https://api.propublica.org/congress/v1/115/bills/hr3943.json" -H "X-API-Key: redacted"
```

```json
{
   "status":"OK",
   "copyright":"Copyright (c) 2017 Pro Publica Inc. All Rights Reserved.",
   "results":[
      {
         "sponsor": "Beto O&#39;Rourke",
```

**Comment by konklone** [comment]
I also see it on a member endpoint, when listing **committee** names:

```
curl "https://api.propublica.org/congress/v1/members/O000170.json" -H "X-API-Key: redacted"
```

```json
           "committees": [
           {
             "name": "Committee on Veterans&#39; Affairs",
             "code": "HSVR",
             "api_uri": "https://api.propublica.org/congress/v1/113/house/committees/HSVR.json",
             "rank_in_party": 10,
             "begin_date": "2013-01-14",
             "end_date": "2015-01-03"
           },
```

**Comment by dwillis** [comment]
For hr3943 I think that's a caching issue. Here's what I see: 
![screen shot 2017-10-24 at 4 40 26 pm](https://user-images.githubusercontent.com/2214/31966916-40d7ccee-b8da-11e7-89e2-ce862235ab3b.png)

**Comment by dwillis** [comment]
Ok, lemme get those.

**Comment by dwillis** [comment]
Those should be fixed now.

**Comment by konklone** [comment]
Confirmed!
