### ISSUE TITLE
Lobbying client/registrant name is not encoded correctly and fails to parse as JSON

### ISSUE THREAD

**Issue by mattheiler** [propublica/congress-api-docs#240]
Using the following endpoint...

https://api.propublica.org/congress/v1/lobbying/latest.json

The lobbying client/registrant name is not encoded correctly and fails to parse as JSON. Double quotes need to be escaped.

A few examples are...

"name": "Midfield Consulting LLC "fka Mr. Michael Joyce""
"name": "Open Access Technology International, Inc. ("OATI")"
"name": "FMR LLC ("Fidelity Investments")"
"name": "Mr. Lionel "Leo" Aguirre"

**Comment by dwillis** [comment]
Thanks, @mattheiler - we've deployed a fix and it should be live in about 30 minutes or so.

**Comment by mattheiler** [comment]
Thanks! Seems like it's fixed for client, but maybe not registrant?

```
"lobbying_client": {
    "name": "The Coalition Against Domain Name Abuse (\"CADNA\")",
    "general_description": ""
},
"lobbying_registrant": {
    "name": "The Coalition Against Domain Name Abuse ("CADNA")",
    "general_description": ""
},
```

**Comment by dwillis** [comment]
Yep, we'll get that, too.

**Comment by mattheiler** [comment]
Working great, thanks! Not sure if it's related, but one of the lobbyist names for the following requests have a similar issue:

https://api.propublica.org/congress/v1/lobbying/300983124.json

```
{
    "name": "Prentiss W. Bolin Jr.\",
    "covered_position": ""
},
```

https://api.propublica.org/congress/v1/lobbying/300956561.json

```
{
    "name": "\ \",
    "covered_position": ""
},
```

**Comment by dwillis** [comment]
Alright, those should be fixed shortly. What else you got? :-)

**Comment by mattheiler** [comment]
That worked! Looks like general description might need it, too.

https://api.propublica.org/congress/v1/lobbying/300936425.json

```
"lobbying_client": {
    "name": "AmeriMetro ",
    "general_description": ""transportation", "manufacturing", " green technology" "
},
"lobbying_registrant": {
    "name": "M.A.Walker & Associates, LLC ",
    "general_description": ""transportation","manufacturing","green technology""
},
```

**Comment by dwillis** [comment]
Ok, think we've got that, too.

**Comment by mattheiler** [comment]
Lobbying registrant is working, but I still see this for the client of this entry:
https://api.propublica.org/congress/v1/lobbying/300936425.json
```
      "lobbying_client": {
        "name": "AmeriMetro ",
        "general_description": ""transportation", "manufacturing", " green technology" "
      },
      "lobbying_registrant": {
        "name": "M.A.Walker & Associates, LLC ",
        "general_description": "\"transportation\",\"manufacturing\",\"green technology\""
      },
```
